### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by hackman2112** [transpect/docx2tex#13]
Hi, I'm trying to install docx2tex on my Mac running El Capitain.  Towards the end I get this:

Submodule path 'mml2tex': checked out '03430be79a70b283679cfc1cb1529da5a044f41f'
Cloning into 'schema/hub'...
The authenticity of host 'github.com (192.30.252.130)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.252.130' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:le-tex/Hub.git' into submodule path 'schema/hub' failed

I'm not sure if this is a problem on my end or not, as I'm something of a newbie to Github.

**Comment by hackman2112** [comment]
Also if I try to run it here's what goes in the log:

ERROR: docx2hub/xpl/single-tree.xpl:49:79:err:XS0052:Cannot import: http://transpect.io/calabash-extensions/transpect-lib.xpl
ERROR:     cause: I/O error reported by XML parser processing http://transpect.io/calabash-extensions/transpect-lib.xpl: http://www.le-tex.de/en/transpect.htmlcalabash-extensions/transpect-lib.xpl
ERROR: It is a static error if the URI of a p:import cannot be retrieved or if, once retrieved, it does not point to a p:library, p:declare-step, or p:pipeline.
ERROR: Underlying exception: I/O error reported by XML parser processing http://transpect.io/calabash-extensions/transpect-lib.xpl: http://www.le-tex.de/en/transpect.htmlcalabash-extensions/transpect-lib.xpl

**Comment by gimsieke** [comment]
Hi Greg, the first issue that you are reporting is probably due to https://github.com/transpect/docx2tex/blob/master/.gitmodules#L24 – the submodule is attached via ssh instead of HTTP, like the other submodules. This only works for someone who has stored their ssh key with their github account. We’ll fix this, it will also be an HTTP URL.

The second issue is an indication that the XML catalog is not being used. In your checked-out copy, is there a file calabash-frontend/xmlcatalog/catalog.xml? How did you exactly invoke d2t, i.e., from which directory, using which command line? 

We don’t use Macs too often, but we’ll be able to investigate further on a Mac tomorrow if it seems to be an issue related to our lack of properly supporting the Mac…

**Comment by gimsieke** [comment]
Ok, I updated the submodule URL. I don’t know exactly how you can update this so that your copy reflects this change. The numerous git incantations and which to select for which occasion is a thing that is still quite arcane to me. git submodules tend to make matters even more complicated.
First, do a
```
git pull
```
so that your .gitmodules file gets updated. Then you can try
```
git submodule foreach --recursive git checkout master
```
and/or 
```
git submodule foreach git pull origin master
```
If that doesn’t help, then maybe
```
git submodule update --init --recursive
```
or checking out a fresh copy altogether, as per https://xkcd.com/1597/

**Comment by hackman2112** [comment]
Hi Gerrit, thank you for your quick response.  I'll try the new repository right away.

Yes, catalog.xml exists right where you said it should.

I invoked d2t right from the command line, in the directory that d2t actually exists, and the invocation was really simple:

./d2t -o a.tex a.docx

**Comment by gimsieke** [comment]
In the meantime, I checked out a fresh version and I was able to reproduce your 2nd issue (that is related to the XML catalog). Will fix it soon.

**Comment by gimsieke** [comment]
(btw, nice avatar…)

**Comment by gimsieke** [comment]
Ok, should be fixed now. Sorry that it didn’t run ok right from the start. I blame git submodules.

**Comment by hackman2112** [comment]
Installs perfectly now!

This type of code is such an important and useful tool for those of us who want to write serious scientific documents.  I've starred it and intend to tell everyone I know about it.

Thanks!

**Comment by gimsieke** [comment]
Please don’t hesitate to report further errors, in particular incorrect mappings to LaTeX, since there will still be some for sure…
