### ISSUE TITLE
lost newline

### ISSUE THREAD

**Issue by gamboz** [transpect/docx2tex#27]
In the following file, a newline is lost between "...Fast ICA Algorithm" and "FastICA disintegrates...":
https://medialab.sissa.it/owncloud/index.php/s/PXm3ktw0LFYXVti

However, please note that in the original docx, there are a couple of spaces missing in "3.1Denoisingby" (probably a typo), but when I tried to add them (to get "3.1 Denoising by") and save the file, the missing newline magically appears in the TeX translation and I can see no error.

**Comment by mkraetke** [comment]
Our list generator treated this first as list because of the indent and then more specifically as variable list due to the tab. Later in the conversion, the list is resolved because it contains only one list point. In the first place, it shouldn't be converted as variable list because of the tab at the end of the line. I've fixed this issue and the new line is now retained.
