### ISSUE TITLE
ERROR: An empty sequence is not allowed as the third argument of replace()

### ISSUE THREAD

**Issue by j3mdamas** [transpect/docx2tex#3]
I am trying to convert a .docx file that is an article with equations, figures, and even references introduced with Endnote.

Using the master (since with the last pre-release (0.3), I was getting the same reported error that was solved recently), and running:

$ docx2tex-master/d2t -o test test.docx

I am getting the following errors:
ERROR: docx2tex-master/xproc-util/load/xpl/load.xpl:0:load-error:Could not load file:/usr/people/jmdamas/docx2tex-master/conf/conf.csv (file:///usr/people/jmdamas/docx2tex-master/xproc-util/load/xpl/load.xpl) dtd-validate=false
ERROR: file:///usr/people/jmdamas/docx2tex-master/mml2tex/xsl/mml2tex.xsl:339:err:XPTY0004:An empty sequence is not allowed as the third argument of replace()
ERROR: An empty sequence is not allowed as the third argument of replace()
ERROR:     cause: file:///usr/people/jmdamas/docx2tex-master/mml2tex/xsl/mml2tex.xsl:339:err:XPTY0004:An empty sequence is not allowed as the third argument of replace()
ERROR: An empty sequence is not allowed as the third argument of replace()
ERROR:     cause: file:///usr/people/jmdamas/docx2tex-master/mml2tex/xsl/mml2tex.xsl:339:err:XPTY0004:An empty sequence is not allowed as the third argument of replace()
ERROR: Pipeline failed: An empty sequence is not allowed as the third argument of replace()
ERROR: Underlying exception: An empty sequence is not allowed as the third argument of replace()

In the first ERROR, I don't understand why the file can't be loaded, since it is there.
The other errors are all related to a replace function, but I can't understand the origin.

I tried to run with an a shorter version of the .docx (just the first 5 or 6 pages, with some equations), and I didn't get any errors. I tried to remove the Endnote references only (I thought they might be a problem) and tested it, and it gave me the errors again. I could go in a trial-and-error mode, trying to identify which part of the document is causing the problem, but I don't think that's a solution.

Can you give me some tips on how to solve this?

Oh, I am running this on an Ubuntu 12.04 with JAVA 1.7.0_80.

Meanwhile, I am using an older (?) version of this software in codeplex (https://docx2tex.codeplex.com/releases/view/19618), that is working well on Windows.

**Comment by gimsieke** [comment]
It will be easiest to investigate if you send us the file. If you send it to letexml @ le-tex.de, @mkraetke and I will receive it. We’ll treat it confidentially, of course.

**Comment by j3mdamas** [comment]
It's a published paper, so it's cool. I will send it there.
Cheers

**Comment by gimsieke** [comment]
It’s having problems converting the cases environment in (5). There is an `<mml:mfenced open="{" close="" separators="|">` element that contains an `<mml:table>` with two rows. I’m not sure whether this is the best representation of `cases` that MathML has to offer, but anyway. We should recognize it and convert it to a proper `cases` environment.

Currently [the template that is handling `mml:mfenced`](https://github.com/transpect/mml2tex/blob/master/xsl/mml2tex.xsl#L233) does not expect empty attributes for `@open` or `@close`. I’m going to change that, too, so that even if we don’t recognize a `cases` environment, the process will still not crash.

**Comment by j3mdamas** [comment]
Oh, I think I follow what you mean: there's an equation object with a system of equations that is causing the problem. I think it is common notation to have an open bracket before the equations without having a close bracket afterwards, so I think it makes sense to accept an empty attribute for the @close.

Thanks!

**Comment by mkraetke** [comment]
Added a template to resolve tables with the style 'docx2tex_equation-table'. The template takes a table and resolves it except the embedded equations. Perhaps this could be a proper workaround for you?

**Comment by gimsieke** [comment]
What @mkraetke didn’t mention: the original issue has been resolved. But there is another issue with the invisible tables that you used to insert the equation numbers. If you assign a specific table style (`docx2tex_equation-table`) to them, they will be dissolved, leaving behind only the equation. I haven’t checked what happens if you don’t unwrap these tables. It could be that the converter will then generate display equations (`$$…$$`) within a `tabular` environment, which apparently is illegal. We should make sure that they will become inline equations if the invisible tables aren’t unwrapped.

**Comment by j3mdamas** [comment]
As you can guess, the invisible tables to insert the equations and equation numbers was a work-around at the time, since MS Word did (and does?) not support numbering for equations. For sure I will need to curate the .tex after the conversion, I did not think otherwise.

So, can I download the current master and use it on my document?

**Comment by mkraetke** [comment]
As far as I know, MS Word does not support numbering of equations. You're table method is commonly used among authors for that reason. You can now apply the table style `docx2tex_equation-table` to automatically dissolve the table. Additionally, equations in tabular environments appear now only with single `$`

**Comment by j3mdamas** [comment]
Sorry for the delay testing. This issue is solved (it runs). But I still identify three issues with this file I sent you. Should I open separate threads for them?

**Comment by gimsieke** [comment]
Yes, go ahead please.
