### ISSUE TITLE
Symbols are  not correct  translated ?

### ISSUE THREAD

**Issue by AngeloGomes** [transpect/docx2tex#69]
I noticed the greek symbols are not converted correctly.

Example: 
Delta symbol is converted to \Updelta
theta symbol is converted to \uptheta
and several other symbols.

for some reason, I always get "\up" ou "\Up" prefix,

**Comment by gimsieke** [comment]
Do you have a sample docx document that will help us reproduce the issue? Either attach it here or send it to letexml at le-tex dot de.

**Comment by mkraetke** [comment]
We use the Upgreek package rather than `\mathrm` for upright greek symbols. The upgreek package is referenced in the preamble, so you just have to install the package from CTAN. In most tex distributions it should be included. If you prefer other mappings for greek characters, you can write your own character map. Here is a brief example for a custom configuration:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<set xmlns="http://transpect.io/xml2tex">
  
  <import href="docx2tex/conf/conf.xml"/>
  
  <charmap>
    <char character="&#x394;" string="${\Delta}$"/>
  </charmap>
  
</set>
```
