### ISSUE TITLE
Use of \left and \right for delimiters/fences -- Math environment -- eg: $\left(a\right)$

### ISSUE THREAD

**Issue by rishinair** [transpect/docx2tex#74]
Normally \left and \right are not required for delimiters unless there are fractions, square roots, large operators like \sum, \prod etc. within the delimiters. For example:

1. $\lelft(\sum_{i=0}\right)$ is correct.
2. But $\left(a\right)$ is not correct. The correct usage is $(a)$.
3. $\left[a_b\right] is not correct. The correct usage is $[a_b]$.

This was correct in the previous version, however \left and \right are unnecessarily appearing in the simple cases as well in 1.6 version.

I have attached an example, [delimiter.zip](https://github.com/transpect/docx2tex/files/5931051/delimiter.zip), which contains delimiter.docx, delimiter-new.tex and delimiter-old.tex. 

delimiter-old.tex is the correct conversion. 

Could you please look into it?

**Comment by rishinair** [comment]
Any update please?

**Comment by mkraetke** [comment]
Thanks for your report. I'll have a look into your issue and try to fix this.

**Comment by mkraetke** [comment]
I've changed the default behaviour for handling delimiters in display equations. You just need to update the docx2tex master branch and you'll see the regular parenthesis as you wanted. Since the last release was just published two weeks ago, I'll wait what other users say to this change and planning the next major release for this summer.

**Comment by rishinair** [comment]
Thank you so much.
