### ISSUE TITLE
Title, author and affiliation details completely missing in one article - Important

### ISSUE THREAD

**Issue by rishinair** [transpect/docx2tex#79]
The content tagged  in &lt;mc:AlternateContent>...&lt;/mc:AlternateContent> in the word/document.xml has gone missing completely in the intermediary XML and in the  final TeX file. Due to the rights issue, I am not able to provide the word file to you. But I can provide a part of the document.xml. Would this be helpful for you to debug?

I have attached [d.zip](https://github.com/transpect/docx2tex/files/5982122/d.zip)  which contains document.xml (only a part of the file).

In the previous version (docx2tex --- ``Garbage In, Garbage Out''), content in the above elements are available.

**Comment by mkraetke** [comment]
The author stored these information in a Word drawing which appears as `<w:drawing>`  in `<mc:AlternateContent>`. `<mc:AlternateContent>` provides fallbacks for older versions of MS Word. `<w:drawing>` is a container which stores DrawingML code. My former colleague @arualmeyer built a DrawingML to SVG transformation for our docx2hub module. This transformation is also active for docx2tex. I'm aware that TeX is not able to convert SVG images but I decided to store the embedded SVGs as external files and leave it to the user to convert them with his favorite image converter.

However, it seems that the SVG transformation wasn't able to extract the text from the DrawingML code. I would suggest the workaround that you copy the text yourself in regular paragraphs and I leave this issue open until this problem is fixed.

**Comment by gimsieke** [comment]
I’m not sure what the LaTeX-generating code of the previous version made of this text-in-graphics content, but it’s possible that there was some usable output.

A short-term solution then might be to offer a switch that disables the new SVG generation.

**Comment by gimsieke** [comment]
It turned out that there already was a `create-svg` option in docx2hub. But it was disregarded/not implemented. I implemented it. The option now expects a boolean value (can also be the strings 'true'/'false').

**Comment by mkraetke** [comment]
Status quo is now that text boxes are omitted from DrawingML to SVG conversion even though they appear within a `w:drawing`. This should render your text and besides DrawingML is stored as SVG and referenced properly:
```latex
Real-time Video Super Resolution Network using Recurrent Multi-Branch Dilated Convolutions

\begin{center}
\#YYYYY XXXX, \#AAAA Xbbbbb, *\&Kkkkk-Ttt Muuu, \&Simmm Lll
\end{center}

\begin{center}
*Corresponding author: gggggg@texxxxnsdcdddddent.com
\end{center}

\begin{center}
\#College of Computer Science and Software Engineering
\end{center}

\begin{center}
Shenzhen University, China
\end{center}

\begin{center}
\&Tencent Music Entertainment, Shenzhen, China
\end{center}

\includegraphics{drawing-svg-1.svg}
```

**Comment by rishinair** [comment]
Thank you so much for the solution, Gerrit and Martin.

My team is very much pleased with your speed in resolving problems :)
