### ISSUE TITLE
Chinese document error

### ISSUE THREAD

**Issue by benzxiaojunjun** [transpect/docx2tex#88]
When there is Chinese in the document, the Chinese is lost after the output TeX file is compiled into PDF.

**Comment by gimsieke** [comment]
Please attach a sample document so that we can reproduce this.

**Comment by benzxiaojunjun** [comment]
[test.docx](https://github.com/transpect/docx2tex/files/6616418/test.docx)
Thanks a lot!I use this command for the conversion:
**./d2t -o /home/benz/output test.docx**

**Comment by mkraetke** [comment]
We have not so much experience with Chinese text. However, I would recommend to change the document class to `ctexart` and use `lualatex` or `xelatex` to render the PDF, since both support UTF-8 and OpenType fonts directly:

1. Change the document class to `ctexart`

```diff
- \documentclass{scrbook}
+ \documentclass{ctexart}
```

2. render for example with `lualatex`

```bash
$ lualatex test.tex
```

**Comment by benzxiaojunjun** [comment]
> We have not so much experience with Chinese text. However, I would recommend to change the document class to `ctexart` and use `lualatex` or `xelatex` to render the PDF, since both support UTF-8 and OpenType fonts directly:
> 
> 1. Change the document class to `ctexart`
> 
> ```diff
> - \documentclass{scrbook}
> + \documentclass{ctexart}
> ```
> 
> 1. render for example with `lualatex`
> 
> ```shell
> $ lualatex test.tex
> ```

**Comment by benzxiaojunjun** [comment]
It works!Thanks a lot!Have a good day!
